name: ForgeMend
version: '${version}'
main: xyz.hynse.forgemend.ForgeMend
api-version: 1.19
folia-supported: true
permissions:
  forgemend.use:
    description: Allows a player to use the repair feature
    default: true
